# Add account credentials and API keys here.
# See http://railsapps.github.io/rails-environment-variables.html
# This file should be listed in .gitignore to keep your settings secret!
# Each entry sets a local environment variable.
# For example, setting:
# GMAIL_USERNAME: Your_Gmail_Username
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]

# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
MANDRILL_USERNAME: Your_Username
MANDRILL_APIKEY: Your_API_Key
DOMAIN_NAME: example.com
ADMIN_NAME: First User
ADMIN_EMAIL: user@example.com
ADMIN_PASSWORD: changeme
PAPERCLIP_PATH: ":rals_root/public/system/"
PAPERCLIP_STORAGE: filesystem
S3_BUCKET: amazon_s3_bucket_name
S3_ACCESS_KEY_ID: s3_access_key_id
S3_ACCESS_KEY_SECRET: s3_access_key_secret
EXCEPTION_RECIPIENT: adam@makeascene.com

# Passed along with the auto-tracking system in the HTTP header
TRACKING_USER_AGENT: "Reconveyance tracking service."
